---
- name: delete load balancers
  hosts: localhost
  gather_facts: false
  tags: [cleanup, loadbalancer]
  tasks:
    - name: delete load balancer
      include_role:
        name: loadbalancer/cleanup
      loop: "{{ loadbalancers }}"
      loop_control:
        loop_var: loadbalancer

- name: delete servers
  hosts: localhost
  gather_facts: false
  tags: [cleanup, server]
  tasks:
    - name: delete servers
      os_server:
        state: absent
        name: "{{ item.name }}"
      loop: "{{ servers }}"

- name: delete volume
  hosts: localhost
  gather_facts: false
  tags: [cleanup, volume]
  tasks:
    - name: delete volume
      os_volume:
        state: absent
        name: test_volume

- name: delete network resources
  hosts: localhost
  gather_facts: false
  tags: [cleanup, network]
  tasks:
    - name: delete routers
      os_router:
        state: absent
        name: "{{ item.name }}"
      loop: "{{ routers }}"

    - name: delete subnets
      os_subnet:
        state: absent
        name: "{{ item.1.name }}"
      loop: "{{ networks|subelements('subnets') }}"

    - name: delete networks
      os_network:
        state: absent
        name: "{{ item.name }}"
      loop: "{{ networks }}"

    - name: delete security groups
      os_security_group:
        state: absent
        name: "{{ item.name }}"
      loop: "{{ security_groups }}"
