---
## This playbook cleans up all the resources created by "setup.yml"
## in this directory.
- hosts: localhost
  gather_facts: false
  tasks:
    - tags: [lb]
      include_role:
        name: loadbalancer/cleanup
      loop: "{{ loadbalancers }}"
      loop_control:
        loop_var: loadbalancer

    - tags: [server]
      os_server:
        state: absent
        name: "{{ item.name }}"
      loop: "{{ servers }}"

    - tags: [network]
      os_router:
        state: absent
        name: "{{ item.name }}"
      loop: "{{ routers }}"

    - tags: [network]
      os_subnet:
        state: absent
        name: "{{ item.1.name }}"
      loop: "{{ networks|subelements('subnets') }}"

    - tags: [network]
      os_network:
        state: absent
        name: "{{ item.name }}"
      loop: "{{ networks }}"

    - tags: [secgroup]
      os_security_group:
        state: absent
        name: "{{ item.name }}"
      loop: "{{ security_groups }}"
