---
## This playbook cleans up all the resources created by "setup.yml"
## in this directory.
- hosts: localhost
  gather_facts: false
  tasks:
    - tags: [lb]
      os_loadbalancer:
        state: absent
        name: test_lb
        vip_network: test_lb_net
        listeners: "{{ item.listeners }}"
      loop: "{{ loadbalancers }}"

    - tags: [server]
      os_server:
        state: absent
        name: "{{ item.name }}"
      loop: "{{ servers }}"

    - tags: [network]
      os_router:
        state: absent
        name: "{{ item.name }}"
      loop: "{{ routers }}"

    - tags: [network]
      os_subnet:
        state: absent
        name: "{{ item.1.name }}"
      loop: "{{ networks|subelements('subnets') }}"

    - tags: [network]
      os_network:
        state: absent
        name: "{{ item.name }}"
      loop: "{{ networks }}"
