---
- hosts: localhost
  tasks:
    - meta: refresh_inventory

- hosts: os_test_targets
  become: true
  tags: [test]
  tasks:
    - name: install darkhttpd on test servers
      package:
        name: darkhttpd
        state: installed

    - name: create /var/www
      file:
        path: /var/www
        state: directory

    - name: create index.html
      copy:
        dest: /var/www/index.html
        content: |
          load balancer test
          This is {{ inventory_hostname }}.

    - name: start darkhttpd
      service:
        name: darkhttpd
        enabled: true
        state: started

- hosts: localhost
  tags: [test, test_lb]
  tasks:
    - include_role:
        name: loadbalancer
      loop: "{{ loadbalancers }}"
      loop_control:
        loop_var: loadbalancer

    - name: check that load balancer responds
      uri:
        url: "http://{{ item.floating_ip }}/"
        return_content: true
      register: response
      loop: "{{ loadbalancers }}"

    - name: validate response content
      assert:
        that: '"load balancer test" in item.content'
      loop: "{{ response.results }}"
