---
- hosts: localhost
  tasks:
    - meta: refresh_inventory

- hosts: os_test_targets[0]
  tasks:
    - name: verify that jumbo frames work
      command: >-
        ping -M do -s 8972 -c 2 {{ hostvars[groups.os_test_targets.1].ansible_host }}
      changed_when: false
