---
- name: remove listeners
  os_listener:
    state: absent
    name: "{{ item.name }}"
    loadbalancer: "{{ loadbalancer.name }}"
    protocol: "{{ item.protocol }}"
    protocol_port: "{{ item.protocol_port }}"
  loop: "{{ loadbalancer.listeners }}"

- name: remove pools
  os_pool:
    state: absent
    name: "{{ item.pool.name }}"
    listener: "{{ item.name }}"
    protocol: "{{ item.protocol }}"
  loop: "{{ loadbalancer.listeners }}"

- name: remove loadbalancer
  os_loadbalancer:
    state: absent
    name: "{{ loadbalancer.name }}"
    vip_network: "{{ loadbalancer.vip_network }}"
  register: created_lb
